name: Release Android-dev
on:
  # 手动触发
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      # 使用本项目
      - uses: actions/checkout@v5.0.0

      # 设置Flutter环境
      - uses: subosito/flutter-action@v2.14.0
        with:
          # 要使用的Flutter版本
          flutter-version: 3.27.4
          # Flutter构建发布渠道
          channel: # 可选，默认为stable

      # 设置JDK环境
      - name: 设置JDK
        uses: actions/setup-java@v5.0.0
        with:
          distribution: 'zulu'
          java-version: 17

      # 获取Flutter依赖
      - run: flutter pub get

      # 从GitHub Secrets恢复签名密钥库
      - name: 恢复签名密钥库
        run: |
          echo "$KEYSTORE_BASE64" | base64 --decode > android/app/keystore.jks
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}

      # 从GitHub Secrets生成keystore.properties文件
      - name: 生成keystore.properties
        run: |
          echo "storeFile=./keystore.jks" > android/keystore.properties
          echo "storePassword=${KEYSTORE_PASSWORD}" >> android/keystore.properties
          echo "keyAlias=${KEY_ALIAS}" >> android/keystore.properties
          echo "keyPassword=${KEY_PASSWORD}" >> android/keystore.properties
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      # 构建APK文件
      - name: 构建APK
        run: flutter build apk --release --split-per-abi

      # 上传x86_64架构的APK文件
      - name: 上传x86_64架构APK
        uses: actions/upload-artifact@v4.6.2
        with:
          name: app-x86_64-release
          path: build/app/outputs/flutter-apk/app-x86_64-release.apk

      # 上传armeabi-v7a架构的APK文件
      - name: 上传armeabi-v7a架构APK
        uses: actions/upload-artifact@v4.6.2
        with:
          name: app-armeabi-v7a-release
          path: build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk

      # 上传arm64-v8a架构的APK文件
      - name: 上传arm64-v8a架构APK
        uses: actions/upload-artifact@v4.6.2
        with:
          name: app-arm64-v8a-release
          path: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
